version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date` 
      - mvn test 
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - mvn package
artifacts: 
  files:
    - appspec.yml
    - target/Spring3HibernateApp.war
  discard-paths: yes
